web:
  voila-homepage:
    url: https://dev-voila-web.machtwatch.net
    path:
      login: /account/login

endpoints:
  login:
    url: https://dev-voila-auth.machtwatch.net/login?&method=password&client=web

account_discovery:
  data_1:
    username: irsyad@machtwatch.co.id
    password: voila-UF5

account:
  data_1:
    username: irsyad@machtwatch.co.id
    password: voila-UF5

account_platform:
  data_1:
    username: voilatesting123@gmail.com
    password: Voila99!