#GENERAL
DOMAIN_NAME: Voila Reseller Platform
DOMAIN_REPORT: voila-reseller
WEB_BASE_URL_VOILA_RESELLER: https://stg-biz-reseller.machtwatch.net/
API_BASE_URL: https://api-stg-biz.machtwatch.net/api
API_XMS_BASE_URL: https://api-stg-biz.machtwatch.net/api/xms
API_XMS_TOKEN_URL: https://stg-mw-xms.machtwatch.net/api/v1/xms/auth/login
ASSERT_URL_WAIT_TIME: 3

#ENVIRONMENT DATA
XMS_USERNAME: qa.reseller.automation@machtwatch.co.id
XMS_PASSWORD: R2V<T3jT

VALID_USERNAME: automationtest
VALID_PASSWORD: Test12345!@#

INVALID_USERNAME: ini invalid username staging
INVALID_PASSWORD: ini-invalid-password-staging

NEW_PASSWORD: Test-123456

RESELLER_NAME: automationtest
RESELLER_PHONE: 08127282722

PRODUCT_SKU_AVAILABLE: AUTOMATION-001
PRODUCT_NAME_AVAILABLE: AUTOMATION PRODUCT - DO NOT TOUCH 01
PRODUCT_GENDER_AVAILABLE: Man
PRODUCT_CATEGORY_AVAILABLE: Shoes
PRODUCT_DESIGNER_AVAILABLE: Adidas
PRODUCT_PRICE_AVAILABLE: 510000

PRODUCT_DISCOUNT_SKU_AVAILABLE: AUTOMATION-DISCOUNT-004
PRODUCT_DISCOUNT_NAME_AVAILABLE: AUTOMATION DISCOUNTED PRODUCT - DO NOT TOUCH 04
PRODUCT_DISCOUNT_GENDER_AVAILABLE: Man
PRODUCT_DISCOUNT_CATEGORY_AVAILABLE: Shoes
PRODUCT_DISCOUNT_DESIGNER_AVAILABLE: Adidas
PRODUCT_DISCOUNT_PRICE_AVAILABLE: 1200000
PRODUCT_DISCOUNT_MARKET_PRICE_AVAILABLE: 1500000

# out of stock
PRODUCT_SKU_OOS: AUTOMATION-007
PRODUCT_NAME_OOS: AUTOMATION PRODUCT - DO NOT TOUCH 07 - OOS
PRODUCT_GENDER_OOS: Woman
PRODUCT_CATEGORY_OOS: Clothes
PRODUCT_DESIGNER_OOS: Nike
PRODUCT_PRICE_OOS: 4500

PRODUCT_DISCOUNT_SKU_OOS: AUTOMATION-DISCOUNT-005
PRODUCT_DISCOUNT_NAME_OOS: AUTOMATION DISCOUNTED PRODUCT - DO NOT TOUCH 05 - OOS
PRODUCT_DISCOUNT_GENDER_OOS: Woman
PRODUCT_DISCOUNT_CATEGORY_OOS: Clothes
PRODUCT_DISCOUNT_DESIGNER_OOS: Nike
PRODUCT_DISCOUNT_PRICE_OOS: 6000
PRODUCT_DISCOUNT_MARKET_PRICE_OOS: 10000

# last item in stock
PRODUCT_SKU_LIS: AUTOMATION-003
PRODUCT_NAME_LIS: AUTOMATION PRODUCT - DO NOT TOUCH 03 - LAST ITEM IN STOCK
PRODUCT_GENDER_LIS: Unisex
PRODUCT_CATEGORY_LIS: Accessories
PRODUCT_DESIGNER_LIS: Chanel
PRODUCT_PRICE_LIS: 6500

PRODUCT_DISCOUNT_SKU_LIS: AUTOMATION-DISCOUNT-006
PRODUCT_DISCOUNT_NAME_LIS: AUTOMATION DISCOUNTED PRODUCT - DO NOT TOUCH 06 - LAST ITEM IN STOCK
PRODUCT_DISCOUNT_GENDER_LIS: Unisex
PRODUCT_DISCOUNT_CATEGORY_LIS: Accessories
PRODUCT_DISCOUNT_DESIGNER_LIS: Chanel
PRODUCT_DISCOUNT_PRICE_LIS: 17089
PRODUCT_DISCOUNT_MARKET_PRICE_LIS: 20099

TELEGRAM_PAGE_TITLE_ADMIN_SALES: 'Telegram: Contact @adm_sales'
TELEGRAM_PAGE_TITLE_ADMIN_WAREHOUSE: 'Telegram: Contact @Aadminmb1'

# list unavailable product cart
PRODUCT_VARIANT_ID_OOS: 40692
PRODUCT_VARIANT_ID_UPUBLISHED: 40588
PRODUCT_VARIANT_ID_DRAFT: 40691
