web:
  voila-homepage:
    url: https://dev-voila-web.machtwatch.net
    path:
      login: /account/login

endpoints:
  login:
    url: https://dev-voila-auth.machtwatch.net/login?&method=password&client=web

account_discovery:
  data_1:
    username: discovery01@machtwatch.co.id
    password: voila-UF5

account_order_history:
  data_1:
    username: orderhistory01@mailinator.com
    password: voila-UF5

account_platform:
  data_1:
    username: accplatform01@gmail.com
    password: Voila99!