web:
  voila-homepage:
    base: https://dev-voila-web.machtwatch.net
  login-page:
    base: https://base.com

endpoints:
  login:
    url: https://url.com:port/login_path

account_discovery:
  data_1:
    username: irsyad@machtwatch.co.id
    password: voila-UF5

account:
  data_1:
    username: irsyad@machtwatch.co.id
    password: voila-UF5