name: Pull Request Checker

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  code-analysis:
    name: Code Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Gemfile for Code Checker
        run: |
          mv Gemfile Gemfilee
          mv GemfileForChecker Gemfile
          cat Gemfile

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install Bundler
        run: |
          gem install bundler -v '2.4.22'

      - name: Bundle Install
        if: success()
        run: bundle install

      - name: Execute RuboCop Code Analysis
        run: |
          rubocop --fail-level warning || (echo "RuboCop failed with warnings/errors" && exit 1)

      - name: Execute Reek Code Detector
        run: |
          reek features/ || (echo "Reek failed with warnings/errors" && exit 1)
