name: Pull Request Checker

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  pipeline-checker:
    name: Check code analyzer & detector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config Gemfile for checker
        run: |
          mv Gemfile Gemfilee
          mv GemfileForChecker Gemfile
          cat Gemfile

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install Bundler
        run: |
          gem install bundler -v '2.4.22'

      - name: Bundle Install
        run: bundle install

      - name: Execute code static analyzer & code detector
        run: |
#          rubocop --fail-level warning || (echo "Rubocop failed with warnings/errors" && exit 1)
          rubocop --fail-level warning

      - name: Execute code detector
        run: |
          reek features/ || (echo "Reek failed with warnings/errors" && exit 1)
