name: Rubocop Checker

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  rubocop-checker:
    name: Execute Rubocop Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install Bundler
        run: |
          gem install bundler -v '2.4.22'

      - name: Adjust Ruby Gems Directory Permissions
        run: |
          sudo chmod +t /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0

      - name: Bundle Install
        run: bundle install

      - name: Execute Rubocop
        run: |
          rubocop --format simple --fail-level warning || exit 1
